### ISSUE TITLE
Fiber Strand Count being populated with incorrect value when cable is created.

### ISSUE THREAD

**Issue by jalsup** [MikeMillerGIS/arcade-expressions#37]
When I create a new <Tier> Fiber Cable, the attribute fibercount is being populated with a value of 1 instead of the actual number of strands.  Updating an attribute on cable causes correct value to be populated.

Workflow
1 - Create Access Cable/Fiber using template "Access Fiber Cable".  Enter the following values
Strand Count: 12
Buffer Tube Count: 2
Structure Search Radius: 100
2 - Digitize two points or more points
3 - Finish Sketch
4 - After create has completed, view attribute pane and navigate to field "Fiber Strand Count", notice a value of 1
5 - Update the attribute "Spatial Source" to Unknown, finish update
6 - After update has completed, view attribute pane and navigate to field "Fiber Strand Count", notice a value of 12

**Comment by ted-howard** [comment]
@jalsup I can repro on 2.5 but my Fiber Strand Count is 0 not 1. Are you getting 1 every time? Because that would leave me stumped

**Comment by jalsup** [comment]
Yes, I am getting 1 every time.  Even 0 is not valid, as it should be 12.
