### ISSUE TITLE
Change Fiber count attribute rules to Strand Count and change assignment fields

### ISSUE THREAD

**Issue by jalsup** [MikeMillerGIS/arcade-expressions#39]
In order to simplify the model, we change the Fiber Count, Coax Count and Copper Count fields to just Strand Count.
This requires changes in the following attribute rules
   - CL-UpdateFiberAvailable.js
        [ ] Change name to UpdateStrandsAvailable.js
        [ ] Change line 3 to "// Name: Populate strandsavailable"
        [ ] Change line 4 to read "// Description: Calculates number of Strand features contained within feature with status of available"
        [ ] Change line 6 to read "// Field: strandsavailable"
        [ ] Change line 19 to read "var fiber_available_sql = 'strandstatus = 1';"  Now applies to all asset types
   - CL-UpdateFiberCount.js
        [ ] Change name to UpdateStrandCount.js
        [ ] Change line 3 tp "// Name: Populate strandcount"
        [ ] Change line 4 to read "// Description: Calculates number of strand features contained within feature"
        [ ] Change line 6 to read "// Field: strandcount"
        [ ] Change line 19 to read "var fiber_sql = 'assetgroup = 8;"  Now applies to all asset types
   - CL-UpdateFiberDedicated.js
        [ ] Change name to UpdateStrandsDedicated.js
        [ ] Change line 3 to read "// Name: Populate strandsdedicated"
        [ ] Change line 4 to read "// Description: Calculates number of Strand features contained within feature with status of dedicated"
        [ ] Change line 6 to read "// Field: strandsdedicated"
        [ ] Change line 19 to read "var fiber_available_sql = 'strandstatus = 4';"  Now applies to all asset types
   - CL-UpdateFiberInUse.js
        [ ] Change name to UpdateStrandsInuse.js

        [ ] Change line 6 to read "// Field: strandsinuse"
        [ ] Change line 19 to read "var fiber_available_sql = 'strandstatus = 2';"  Now applies to all asset types
   - CL-UpdateFiberPendingConnect.js
        [ ] Change name to UpdateStrandsPendingConnect.js
        [ ] Change line 3 to read "// Name: Populate strandspendingconnect"
        [ ] Change line 4 to read "// Description: Calculates number of Strand features contained within feature with status of pending customer connect"
        [ ] Change line 6 to read "// Field: strandspendingconnect"
        [ ] Change line 19 to read "var fiber_available_sql = 'strandstatus = 6';"  Now applies to all asset types
   - CL-UpdateFiberPendingDisconnect.js
        [ ] Change name to UpdateStrandsPendingDisconnect.js
        [ ] Change line 3 to read "// Name: Populate strandspendingdisconnect"
        [ ] Change line 4 to read "// Description: Calculates number of Strand features contained within feature with status of pending customer disconnect"
        [ ] Change line 6 to read "// Field: strandspendingdisconnect"
        [ ] Change line 19 to read "var fiber_available_sql = 'strandstatus = 7';"  Now applies to all asset types
   - CL-UpdateFiberReserved.js
        [ ] Change name to UpdateStrandsReserved.js
        [ ] Change line 3 to read "// Name: Populate strandsreserved"
        [ ] Change line 4 to read "// Description: Calculates number of Strand features contained within feature with status of reserved"
        [ ] Change line 6 to read "// Field: strandsreserved"
        [ ] Change line 19 to read "var fiber_available_sql = 'strandstatus = 3';"  Now applies to all asset types
   - CL-UpdateFiberUnusable.js
        [ ] Change name to UpdateStrandsUnusable.js
        [ ] Change line 3 to read "// Name: Populate strandsunusable"
        [ ] Change line 4 to read "// Description: Calculates number of Strand features contained within feature with status of not usable"
        [ ] Change line 6 to read "// Field: strandsunusable"
        [ ] Change line 19 to read "var fiber_available_sql = 'strandstatus = 5';"  Now applies to all asset types

**Comment by ted-howard** [comment]
many of these rules are going away to make way for a single rule that runs on the strand feature. when strand status is changed, an edit will be made to the parent cable. I will be sure to use the Strand Count attributes instead of Fiber Count
